version: 2
jobs:
  build:
    docker:
      - image: hashicorp/terraform
        entrypoint: ["/bin/sh"]
    steps:
      - checkout
      - run: terraform init -backend=false
      - run: terraform validate -check-variables=false
      - run: terraform plan


workflows:
  version: 2
  commit:
    jobs:
      - build
